# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - bloodpressure-ca

on:
  push:
    branches:
      - Development
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.301'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

        # Run NUnit Testing
      - name: Run NUnit Unit Testing
        run: dotnet test BPCalculator.Tests/BPCalculator.Tests.csproj --collect "Code coverage"

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    # Test the Code using Sonar Scanner
      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
          buildCommand: dotnet build .
          projectKey: dfoley84_Calculator
          projectName: Calculator
          sonarOrganisation: dfoley84
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy_to_staging:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bloodpressure-ca'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_926E828855504CC18AB3B0274D9956E1 }}
          package: .
      - name: Selenium Testing
        run: dotnet test ./Selenium.dll --logger:"trx;LogFileName=selenium.trx"

   #Run load Testing on the Production Web Server
  k6_load_test:
    name: k6 Load Testing
    runs-on: ubuntu-latest
    needs: deploy_to_staging
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run k6 cloud test
        uses: k6io/action@v0.1
        with:
          filename: k6.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}

  # Run Pen Testing on the Production WebPage
  Owasp:
    runs-on: ubuntu-latest
    needs: k6_load_test
    steps:
      - name: Web Scanner
        uses: zaproxy/action-baseline@v0.5.0
        with:
          docker_name: owasp/zap2docker-stable:2.10.0
          token: ${{ secrets.TOKEN_GITHUB }}
          target: 'https://bloodpressure-ca-staging.azurewebsites.net'

  #Deploy Application to Production Environment (Approval Needed)
  Deploy_to_Production:
    runs-on: windows-latest
    needs: Owasp
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bloodpressure-ca'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D16DF9738DEF4C678A17CD583CBC8F1C }}
          package: .
