# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  Owasp:
    runs-on: ubuntu-latest
    steps:
      - name: Web Scanner
        uses: zaproxy/action-baseline@v0.5.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          target: 'https://schoolbud.academy/'
